[package]
name = "embroider"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "bindings/*", "app"]

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
crossbeam-channel = "0.5.8"
peg = "0.8.2"
